# Generated by Django 6.1.1 on 2026-09-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acervo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("autor", models.CharField(max_length=100, verbose_name="Autor")),
                ("ano", models.IntegerField(verbose_name="Ano")),
                (
                    "disponivel",
                    models.BooleanField(default=True, verbose_name="Disponível"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("DIGITAL", "Digital"), ("FISICO", "Físico")],
                        default="FISICO",
                        max_length=7,
                        verbose_name="Tipo de acervo",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("000", "000 – Generalidades e Informação"),
                            ("100", "100 – Filosofia e Psicologia"),
                            ("200", "200 – Religião e Teologia"),
                            ("300", "300 – Ciências Sociais e Direito"),
                            ("400", "400 – Linguística e Idiomas"),
                            ("500", "500 – Ciências Puras (Exatas e Naturais)"),
                            ("600", "600 – Ciências Aplicadas (Tecnologia)"),
                            ("700", "700 – Artes e Recreação"),
                            ("800", "800 – Literatura"),
                            ("900", "900 – História e Geografia"),
                        ],
                        default="000",
                        max_length=3,
                        verbose_name="Categoria (CDD)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acervo",
                "verbose_name_plural": "Acervos",
                "ordering": ["titulo"],
            },
        ),
        migrations.DeleteModel(
            name="LivroDigital",
        ),
        migrations.DeleteModel(
            name="LivroFisico",
        ),
    ]
